### ISSUE TITLE
Latest molecule release (v26.8.0) breaks EC2 driver

### ISSUE THREAD

**Issue by tstyczen** [ansible-community/molecule-plugins#379]
Hello,
Since release of molecule v26.8.0, EC2 driver is throwing errors when molecule scenario reach the create part:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.15/x64/bin/molecule", line 6, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/click/core.py", line 1569, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/click/core.py", line 1490, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/click/core.py", line 1970, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/click/core.py", line 1353, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/click/core.py", line 907, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/click_cfg.py", line 660, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/click_cfg.py", line 479, in wrapper
    return func(ctx)
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/command/test.py", line 95, in test
    base.execute_cmdline_scenarios(scenario_name, args, command_args, ansible_args, exclude)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/command/base.py", line 243, in execute_cmdline_scenarios
    _run_scenarios(scenarios, command_args, default_config)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/command/base.py", line 375, in _run_scenarios
    execute_scenario(scenario, shared_state=scenarios.shared_state)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/command/base.py", line 477, in execute_scenario
    execute_subcommand(scenario.config, action)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/command/base.py", line 462, in execute_subcommand
    return command(current_config).execute(args)
           ~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/command/base.py", line 78, in __init__
    self._setup()
    ~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/command/base.py", line 116, in _setup
    self._config.provisioner.manage_inventory()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/provisioner/ansible.py", line 440, in manage_inventory
    self._write_inventory()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/provisioner/ansible.py", line 494, in _write_inventory
    util.write_file(self.inventory_file, util.safe_dump(self.inventory))
                                                        ^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/provisioner/ansible.py", line 263, in inventory
    connection_options = self.connection_options(instance_name)
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule/provisioner/ansible.py", line 343, in connection_options
    d = self._config.driver.ansible_connection_options(instance_name)
  File "/opt/hostedtoolcache/Python/3.13.15/x64/lib/python3.13/site-packages/molecule_plugins/ec2/driver.py", line 224, in ansible_connection_options
    for item in self._config.config.get("platforms", [])
                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'config'
```

I don't reproduce the issue when using docker driver.

**Comment by gmoynihan88** [comment]
Root cause is a rename in molecule 26.8.0, not a removal — `Config.config` became `Config.config_data`:

```python
# molecule 26.6.0 — config.py, Config.__init__
self.config = self._get_config()
...
self.config = self._reget_config()

# molecule 26.8.0
self.config_data = self._get_config()
...
self.config_data = self._reget_config()
```

Confirmed against 26.8.0:

```
>>> c = Config("molecule/default/molecule.yml")
>>> hasattr(c, "config"), hasattr(c, "config_data")
(False, True)
>>> [p["name"] for p in c.config_data.get("platforms", [])]
['instance-a']
```

`ec2` is the only driver in the package affected — `grep -rn "_config\.config" src/molecule_plugins/` returns one hit, `driver.py:224`.

Worth flagging that this also breaks cleanup: `ansible_connection_options` is on the destroy path, so `molecule destroy` raises at the same line and the instances are left running. We've been leaking EC2 instances on every CI run since upgrading.

Happy to send a PR. One question on how you'd want it: the package declares `molecule>=25.1.0` and `config_data` doesn't exist before 26.8, so a straight rename breaks older molecule. Compat shim, or bump the floor to `molecule>=26.8.0`?

**Comment by madrover** [comment]
hi @gundalow 
Could we have https://github.com/ansible-community/molecule-plugins/pull/382 merged? This driver is broken since https://github.com/ansible/molecule/commit/d7811189887df5dafa1230f3871275d8683b3d19

Thanks!
